services:
  web:
    build: 
      context: .
      args:
        - FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - FIREBASE_DATABASE_URL=${VITE_FIREBASE_DATABASE_URL}
        - FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID} # Optional
    ports:
      - "51235:80" # Map host port 3000 to container port 80
    container_name: the-wheel

    #volumes: # Optional: Mount a volume for development to reflect code changes immediately
    #  - ./src:/app/src
    #  - ./public:/app/public
    #depends_on: # Optional: If you have a backend, you can specify dependencies here
      # - backend
    #networks:
    #  - app-network

# Optional: Define a network if you have multiple services
#networks:
#  app-network: